swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
#     transport: mail

# swiftmailer:
#     transport:        gmail
#     username:         *******@gmail.com
#     password:         *************
#     host:             localhost
#     port:             465
#     encryption:       ssl
#     auth-mode:        login
#     spool: { type: 'memory' }
#     stream_options:
#         ssl:
#             allow_self_signed: true
#             verify_peer: false
#             verify_peer_name: false
